services:
  frontend:
    container_name: frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOSTNAME=${HOSTNAME}
      - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    container_name: djangoapp
    build: ./backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_HOST=${PG_HOST}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - HOSTNAME=${HOSTNAME}
      - DJANGO_SETTINGS_MODULE=djangotest.settings

    volumes:
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db

  redis:
    image: 'redis:7.0.0'
    ports:
      - '6380:6379'

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - HOSTNAME=${HOSTNAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile.caddy
    env_file:
      - .env
    ports:
      - '8081:80'
      - '8443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/static
      - media:/app/media
    depends_on:
      - frontend
      - backend

volumes:
  static_volume: {}
  pgdata: {}
  media: {}
  caddy_data: {}
  caddy_config: {}
